--DBA
CREATE ROLE ADMINISTRADOR_BD;

--Dar Permisos a rol
GRANT CREATE SESSION TO ADMINISTRADOR_BD;
GRANT CREATE ANY TABLE TO ADMINISTRADOR_BD;
GRANT CREATE ROLE TO ADMINISTRADOR_BD;
GRANT CREATE USER TO ADMINISTRADOR_BD;
GRANT CREATE VIEW TO ADMINISTRADOR_BD;
GRANT CREATE ANY INDEX TO ADMINISTRADOR_BD;
GRANT CREATE TRIGGER TO ADMINISTRADOR_BD;
GRANT CREATE PROCEDURE TO ADMINISTRADOR_BD;
GRANT CREATE SEQUENCE TO ADMINISTRADOR_BD;

