--CREAR USUARIO
CREATE USER pacifico IDENTIFIED BY contrasena DEFAULT TABLESPACE TALLERTS TEMPORARY TABLESPACE TALLERT_TEMP;
--DAR PERMISOS AL USUARIO ADMINISTRADOR_BD SOBRE TABLESPACES
GRANT UNLIMITED TABLESPACE TO pacifico;


--VOLCAR ADMINISTRADOR_BD A COLECCIONES
GRANT ADMINISTRADOR_BD TO pacifico; 